<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsYxYhTFJFhdor4Kf2/dM'."\n".'WHcWcC182JbIQ4DuDHIGHYpZgJxdf0xCugUqVtRIXI+6A7CVjh3VsApmkeY/DNxt'."\n".'mFbKCxD2TGWV77SXFe2pKFQbfdWmfqdvPe51CH2EX1wKZySoecsEcuxtLQKIHQFg'."\n".'iiBzU6W6kG493hZHyO7N6ikHfOGcyJiyWbSA+12HNKU/O+jYH/2oecQkuW6aW5lN'."\n".'zbaf/HeGy1i9PKA7hvTRikELXr8dWh/krtiypRVwA9y/BYCEDTnwrFKu3HGnzeos'."\n".'bDSRu+26d+YHF3e5kq02nk+G9g4ZU/tO560tgtECBaJHSNl1rFt+pIqqLYW7UyB1'."\n".'DQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
