<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNIkeoOz\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNIkeoOz/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNIkeoOz.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerNIkeoOz\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerNIkeoOz\appAppKernelProdContainer([
    'container.build_hash' => 'NIkeoOz',
    'container.build_id' => 'bb8573bb',
    'container.build_time' => 1689253015,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNIkeoOz');
