<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.factory.sourcehandler' shared service.

$this->services['prestashop.module.factory.sourcehandler'] = $instance = new \PrestaShop\PrestaShop\Core\Module\SourceHandler\SourceHandlerFactory();

$instance->addHandler(($this->services['prestashop.module.sourcehandler.zip'] ?? $this->load('getPrestashop_Module_Sourcehandler_ZipService.php')));

return $instance;
