<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFaRFDEe\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFaRFDEe/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFaRFDEe.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFaRFDEe\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFaRFDEe\appAppKernelProdContainer([
    'container.build_hash' => 'FaRFDEe',
    'container.build_id' => '02b8b003',
    'container.build_time' => 1729415917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFaRFDEe');
