<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSkluBmy\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSkluBmy/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSkluBmy.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSkluBmy\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerSkluBmy\appAppKernelDevDebugContainer([
    'container.build_hash' => 'SkluBmy',
    'container.build_id' => 'a7b9676a',
    'container.build_time' => 1696664725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSkluBmy');
