<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM0PdUcu\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM0PdUcu/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM0PdUcu.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM0PdUcu\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerM0PdUcu\appAppKernelDevDebugContainer([
    'container.build_hash' => 'M0PdUcu',
    'container.build_id' => '63be45b7',
    'container.build_time' => 1729627740,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM0PdUcu');
